LIBS:=`root-config --libs`
INCS:=`root-config --cflags`

main: main.o RandomGen.o IntegralMC.o
	g++ -o main main.o RandomGen.o IntegralMC.o ${INCS} ${LIBS} -std=c++11

main.o: main.cpp RandomGen.h IntegralMC.h Seno.h
	g++ -c -o main.o main.cpp ${INCS} ${LIBS} -std=c++11

RandomGen.o: RandomGen.cpp RandomGen.h
	g++ -c -o RandomGen.o RandomGen.cpp ${INCS} ${LIBS} -std=c++11

IntegralMC.o: IntegralMC.cpp IntegralMC.h 
	g++ -c -o IntegralMC.o IntegralMC.cpp ${INCS} ${LIBS} -std=c++11

clean:
	rm *.o