LIBS:=`root-config --libs`
INCS:=`root-config --cflags`

main: main.o RandomGen.o Esperimento.o
	g++ -o main main.o RandomGen.o Esperimento.o ${INCS} ${LIBS} -std=c++11

main.o: main.cpp RandomGen.h Esperimento.h
	g++ -c -o main.o main.cpp ${INCS} ${LIBS} -std=c++11

RandomGen.o: RandomGen.cpp RandomGen.h
	g++ -c -o RandomGen.o RandomGen.cpp ${INCS} ${LIBS} -std=c++11

Esperimento.o: Esperimento.cpp RandomGen.h Esperimento.h
	g++ -c -o Esperimento.o Esperimento.cpp ${INCS} ${LIBS} -std=c++11

clean:
	rm *.o